#!/usr/bin/env python3

import time

import psutil


def _pgrep(name: str) -> bool:
    for process in psutil.process_iter():
        if process.name() == name:
            return True

    return False


def main() -> None:
    while True:
        if _pgrep("tomate"):
            print("🍅", flush=True)
        else:
            print(" ", flush=True)

        time.sleep(5)


if __name__ == "__main__":
    main()
